development:
  adapter: postgresql
  encoding: unicode
  database: influence_development
  pool: 5
  username: <%= ENV['INFLUENCE_DB_USERNAME'] %>
  password: <%= ENV['INFLUENCE_DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: Influence_test
  pool: 5
  username: Influence
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Influence_production
  pool: 5
  username: Influence
  password:
