development:
  adapter: postgresql
  encoding: unicode
  database: influence_development
  pool: 5
  username: <%= ENV['INFLUENCE_DB_USERNAME'] %>
  password: <%= ENV['INFLUENCE_DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: Influence_test
  pool: 5
  username: <%= ENV['INFLUENCE_DB_USERNAME'] %>
  password: <%= ENV['INFLUENCE_DB_PASSWORD'] %>

production:
  database: <%= ENV['DATABASE_URL'] %>
